
version: '3.8'

services:
  db:
    image: mysql:8.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hitema&2024
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_scripts:/docker-entrypoint-initdb.d


volumes:
  mysql_data:
